### PR TITLE
Create photo_view_swipe.dart

### PR DESCRIPTION
**Pull request by dbilgin**
Initially I thought it would be easier to check with a separate class, if it works out maybe it can be merged to the main `PhotoView`.

I first thought of using `Draggable`, but `GestureDetector` seems to be the way to detect both `scale` and `drag` actions at the same time. After testing for a while, I noticed that if the scale gesture is not made well the widget can assume this is a drag gesture, but I'm not sure how much of a problem this is, might be worth checking out.

Another note is that I had to add `backgroundDecoration: BoxDecoration(color: Colors.transparent),` to `PhotoView`, otherwise it would leave a trace of the background color during dismiss. Instead, I added the `backgroundDecoration` to the `Container`, which fixes this problem.

And the final catch would be that for having a nice look while dragging, we need a transparent background on the page, so the navigation should be made like:

```
Navigator.of(context).push(
  PageRouteBuilder(
    opaque: false,
    pageBuilder: (_, __, ___) => ImageDisplay(),
  ),
);
```

It can simply be tested like below:

```
class ImageDisplay {
...

@override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.transparent,
      body: PhotoViewSwipe(
        heroAttributes: PhotoViewHeroAttributes(tag: 'imageHero'),
        imageProvider: FileImage(
          File(_uri),
        ),
      ),
    );
  }
```

### Note:
Just realised that if the image is zoomed, the pan gesture would immediately start dragging, so as a work-around, I took over `PhotoViewScaleStateController` and if the image is zoomed it wouldn't try to drag and dismiss the image away.

Here is a preview:
swipe

### CODE REVIEW

**Comment by clragon** [comment]
While zooming in will disable dismiss,
double tap to zoom does not disable it.

So if you double tap and then start to pan, 
it will dismiss the picture.

Otherwise this seems like a great addition that I've always wanted.

**Comment by dbilgin** [comment]
Hi @clragon thank you for noticing this! I just fixed it, it should work as intended now :)

**Comment by clragon** [comment]
I tried the new fix and it works in that regard.

However, the swipe isnt renabled anymore, it seems?
Wether dragging it to full view nor double tapping again to restore zoom does reenable swiping.

**Comment by dbilgin** [comment]
@clragon sorry, small typo, should really be fixed now.

**Comment by clragon** [comment]
@dbilgin works awesome!

I wish the snapping back of the image had bouncy physics, but I dont actually know if physics can be applied to this.

**Comment by dbilgin** [comment]
@clragon That's for another PR I think :)

**Comment by clragon** [comment]
As of right now, this should be incompatible with the gallery, correct?
Since the gallery doesnt allow you to return your own PhotoView widget, but instead it you pass a GalleryOptions object. 🤔 

Though this might be easily solved with an additional boolen for the GalleryOptions which switches the gallery from normal to swipe pictures.

**Comment by clragon** [comment]
so, besides that this branch didnt get merged yet, how would this work with the gallery? 🤔

**Comment by markszenteTB** [comment]
Will this be merged?

**Comment by dbilgin** [comment]
As it has been **well** over a year and considering I already have a simple, straightforward solution to this myself, I will be closing this PR.

**Comment by dbilgin** [comment]
@iabdousd this PR is no longer relevant as I have mentioned in my previous comment, hence I closed it, I created a separate implementation from scratch.

**Comment by wangwei2-ola** [comment]
> @iabdousd this PR is no longer relevant as I have mentioned in my previous comment, hence I closed it, I created a separate implementation from scratch.

Thank you for your efforts, is this "separate implementation " now realized?

**Comment by dbilgin** [comment]
Yes @wangwei2-ola check [this](https://github.com/dbilgin/swipe_image_gallery) out.

**Pull request closed without merging**
