### PR TITLE
Set PhotoViewGestureRecognizer dragStartBehavior

### PR DESCRIPTION
**Pull request by FaKenKoala**
According to GestureDector.dragStartBehavior description between DragStartBehavior.start and DragStartBehavior.down, to make image scalable more smoothly, we should set PhotoViewGestureRecognizer dragStartBehavior to DragStartBehavior.start.

### CODE REVIEW

**Comment by FaKenKoala** [comment]
Set gesture point as scale center.

**Comment by FaKenKoala** [comment]
Add AutomaticKeepAliveClientMixin in _PhotoViewState to keep scale state in gallery.

**Comment by FaKenKoala** [comment]
Add borderFlex and photoViewFlex to meet demand of gallery border padding.
The two properties are used in PageController viewportFraction and drawing border widgets.

**Comment by renancaraujo** [comment]
Hello @FaKenKoala. Thanks for the effort!

Even tough the dragStartBehavior is a veryr easonable suggestion, I have to ask you to fix one problem at a PR to better track possible future bugs. 

If you roll back the gallery padding thing (that wont be merged see https://github.com/fireslime/photo_view/issues/42#issuecomment-856242817) I would be happy to merge it.

**Comment by FaKenKoala** [comment]
@renancaraujo Sorry for the late reply. Thanks for the solution about the gallery padding problem. I will create new requests for every problem.

**Pull request closed without merging**
