### PR TITLE
added onScaleEnd callback

### PR DESCRIPTION
**Pull request by SVyatoslavG**
Added onScaleEnd callback in the same fashion as onTapUp and onTapEnd. Tested, working. Please merge in.

### CODE REVIEW

**Comment by 120011676** [comment]
@renancaraujo  Hope to merge and release the version quickly, waiting to use.

All of them are ready to implement request merge. I found that they already have.

#280

**Comment by 120011676** [comment]
onTapUp，Is it there?
@SVyatoslavG

**Comment by SVyatoslavG** [comment]
Sorry, I did not see your message.
Pull request is brought up to date with conflicts resolved.

**Comment by renancaraujo** [comment]
Thank you soo much @SVyatoslavG

**Pull request merged**
