### PR TITLE
fix: flutter 1.20 double tap and other gesture won't work

### PR DESCRIPTION
**Pull request by hongpeifeng**

### CODE REVIEW

**Comment by renancaraujo** [comment]
Although this fixes the problem, I think the issue is on the `HitCornersDetector`, where we return true in `Offset.zero` scenarios. here: https://github.com/renancaraujo/photo_view/blob/0.10.2/lib/src/core/photo_view_hit_corners.dart#L34

I've prepared a refactor on #326 that should fix this.

**Review by edocabhi — APPROVED** [review]
I had the same issue in flutter 1.20.3 and adding this single line fixes it. Please merge this or make necessary changes and publish an updated version of the plugin.

**Comment by Creolophus** [comment]
This works! Please merge it

**Comment by renancaraujo** [comment]
This should be fixed at [0.10.3](https://github.com/fireslime/photo_view/releases/tag/0.10.3)
Closing in favor of the recent release.

**Comment by ZahraVe** [comment]
> Although this fixes the problem, I think the issue is on the `HitCornersDetector`, where we return true in `Offset.zero` scenarios. here: https://github.com/renancaraujo/photo_view/blob/0.10.2/lib/src/core/photo_view_hit_corners.dart#L34
> 
> I've prepared a refactor on #326 that should fix this.

I still have tapping issue on different samsung phones. what should I do to fix this?
I am using ;
photo_view: ^0.12.0
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.2.3 20D91 darwin-arm, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 4.1)
[✓] Connected device (1 available)

**Pull request closed without merging**
