### PR TITLE
fix double tapping in gallery

### LINKED ISSUE #216: [BUG] in gallery, tap is always panning when zoomed
**Describe the bug**
Any tap down, tap up or double tap starts to pan when displaying a zoomed image in a `PhotoViewGallery`. `PhotoViewGalleryPageOptions` callbacks `onTapUp` and `onTapDown` are not called, and it doesn't cycle through zoom on double tap (though all of this works fine when the image is not zoomed in).

**To Reproduce**
1 Open the Gallery example
2 Tap on an image to open it
3 Double tap once to zoom
4 Double tap again

**What is the current behavior?**
It starts to pan, even for an unnoticeable amount of pixels.

**Expected behavior**
It should cycle through zoom, just like it does with a regular `PhotoView` (not in a gallery).

**Which versions of Flutter/Photo View, and which browser / OS are affected by this issue? Did this work in previous versions of Photo View?**
Flutter (Channel beta, v1.11.0, on Microsoft Windows [Version 10.0.18363.476], locale en-GB)
It used to work with photo_view v0.7.0, the bug appeared in v0.8.0, and it's still here in v0.9.0.

### PR DESCRIPTION
**Pull request by clragon**
This MR attempts to fix #216 

Using the Code provided by @deckerst migrated to null safety.

I have adjusted the touch slope factor for panning and it seems to work decently.

### CODE REVIEW

**Comment by ZahraVe** [comment]
I still have tapping issue on samsung phons (android 10). Could you please help me to fix the issue?
I am using ;
photo_view: ^0.12.0
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.2.3 20D91 darwin-arm, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 4.1)
[✓] Connected device (1 available)

**Comment by ZahraVe** [comment]
@clragon  I still have tapping issue on samsung phons (android 10). Could you please help me to fix the issue?
I am using ;
photo_view: ^0.12.0
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.2.3 20D91 darwin-arm, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 4.1)
[✓] Connected device (1 available)

**Comment by clragon** [comment]
@ZahraVe I cannot help you fix this,
this PR has it's own issues.

@renancaraujo said there might be a rewrite in the future 
and that might fix double tapping.

For now there is no solution to this.

**Comment by clragon** [comment]
@ZahraVe you seem to have not understood my message.

There is currently no fix for the double tap issue. 
It is not fixed in any released version.

issue #293 is not related to the double tap issue.
the issue you are looking for is #216.

**Comment by ZahraVe** [comment]
@clragon  Seems I am a bit confiused among all gesture issues related to this plugin. But I got your point. Thanks anyway. so I need to have a look at other options. What is the alternative for this plugin in your opinion? thanks for youe help.

**Pull request closed without merging**
